### ISSUE TITLE
How to set `LAMBDA_EXECUTOR=docker` for lambda ?

### ISSUE THREAD

**Issue by caliburn1994** [localstack/helm-charts#21]
Environments:

```Bash
$ sudo minikube version
minikube version: v1.19.0
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

Errors:
```
An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: my-function
START 7105db6b-e134-4ab2-bf92-0fe3b33b6a3f: Lambda arn:aws:lambda:us-east-1:000000000000:function:my-function started via "local" executor ...
Unable to find executor for Lambda function "my-function". Note that Node.js, Golang, and .Net Core Lambdas currently require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 766, in do_execute
    result = lambda_function(event, context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 780, in generic_handler
    raise ClientError(('Unable to find executor for Lambda function "%s". Note that ' +
localstack.services.awslambda.lambda_api.ClientError: Unable to find executor for Lambda function "my-function". Note that Node.js, Golang, and .Net Core Lambdas currently require LAMBDA_EXECUTOR=docker

END RequestId: 7105db6b-e134-4ab2-bf92-0fe3b33b6a3f
REPORT RequestId: 7105db6b-e134-4ab2-bf92-0fe3b33b6a3f Duration: 0 
```

**Comment by whummer** [comment]
Hi @caliburn1994 , thanks for your message, and apologies for the long delay. Have you been able to get this working? It seems that customizing the `DOCKER_HOST` variable should be the right way to go - does that work in your local Minikube environment? Please keep us posted how it goes - happy to help out more if you can share more details.. Thanks!

**Comment by whummer** [comment]
Hi @caliburn1994 - just a quick follow-up, have you been able to get it running in the meantime? Would be great if you could share your solution here with others as well... Thanks!

**Comment by cmeans** [comment]
Setting the env var `DOCKER_HOST` would seem to be pointless, as (and I am not a Python dev, so could be missing something) it appears that `DOCKER_HOST` is overridden in https://github.com/localstack/localstack/blob/239801c37187caea559898550ef5313631e8bd48/localstack/utils/bootstrap.py#L598

Also, though commented out in https://github.com/localstack/helm-charts/blob/a741d7f079db74cb59eae74a65c6881cd225e195/charts/localstack/values.yaml#L41, `lambdaExecutor` can be set as a Value, as it's still consumed here: https://github.com/localstack/helm-charts/blob/a741d7f079db74cb59eae74a65c6881cd225e195/charts/localstack/templates/deployment.yaml#L72, not that it appears to help at all.

Without being able to override `DOCKER_HOST`, I've not found a way to get the k8s container for LocalStack to see the DinD container in the same Pod, so though I can create Lambda functions, executing them always throws this error in the LocalStack container:

`localstack.utils.docker.ContainerException: Docker not available`

Earlier in the log output one also sees:
`2021-09-05T15:32:45:WARNING:localstack.services.awslambda.lambda_api: Lambda executor configured as LAMBDA_EXECUTOR=docker but Docker is not accessible. Please make sure to mount the Docker socket /var/run/docker.sock into the container.`

The code _appears_ focused on determining if it's running locally or inside Docker, rather than as a container in Kubernetes, which is impacting decisioning.

I would love to be able to run Lambdas inside LocalStack on Kubernetes...is there more we're missing?  Here's my current helm chart settings (using helmfile):

```
  - debug: true
  - lambdaExecutor: docker
  - service:
      type: ClusterIP
  - ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: "localstack.{{ .Namespace }}.ourhost.com"
          paths: [/]
  - persistence:
      enabled: true
  - mountDind:
      enabled: true
```

**Comment by whummer** [comment]
Thanks for digging into this @cmeans !

> Setting the env var DOCKER_HOST would seem to be pointless, as (and I am not a Python dev, so could be missing something) it appears that DOCKER_HOST is overridden in https://github.com/localstack/localstack/blob/239801c37187caea559898550ef5313631e8bd48/localstack/utils/bootstrap.py#L598

Please note that the code above is used from the `localstack start` command line utility to start up the LocalStack Docker container. In other words - this piece of code is irrelevant and should never be executed in case of Kubernetes deployments. 

> Without being able to override DOCKER_HOST, I've not found a way to get the k8s container for LocalStack to see the DinD container in the same Pod, so though I can create Lambda functions, executing them always throws this error in the LocalStack container:

Were you able to give it a try with setting `DOCKER_HOST` for the DinD setup? 

----

@kristapsstrals Regarding this issue - were you able to get more insights as to why the volume is not being bound into the new Docker container? Not sure if the volume mount paths for DinD are relative to the DinD host container, or absolute with respect to the "global" Docker daemon?

> The main issue seems to be that the docker container started from the localstack pod on k8s does not bind the volume into the new docker container.

Thanks for your help!

**Comment by cmeans** [comment]
Thanks for the correction, @whummer .

There seems no point in trying to set `DOCKER_HOST` myself, it appears to be set correctly in the helm chart `deployment.yaml`, correctly adjusting the port depending upon `mountDind.forceTLS.

I don't see it consumed anywhere in the localstack code, but maybe there's a library or something that's using it.

Are there any other env vars/properties that I can set?

In case it helps, here's the LocalStack log (including when I attempt to invoke a Lambda):
[localstack.log](https://github.com/localstack/helm-charts/files/7112166/localstack.log)

**Comment by cmeans** [comment]
@whummer 

With respect to my previously attached log output...I neglected to mention that I've been fishing around env vars attempting to resolve things and had included these settings manually in the `deployment.yaml` for the LocalStack container, with negligible improvements.

```
            - name: MAIN_CONTAINER_NAME
              value: localhost
            - name: HOSTNAME_FROM_LAMBDA
              value: localhost
            - name: LAMBDA_REMOTE_DOCKER
              value: "1"
            - name: LAMBDA_DOCKER_NETWORK
              value: "host"
```

Setting `MAIN_CONTAINER_NAME` at least avoided this error:

`2021-09-05T18:53:56:INFO:localstack.services.awslambda.lambda_executors: Unable to get IP address of main Docker container "localstack_main": Docker not available
`

But, I'm swinging in the dark here, and certainly appreciate any help you can provide.

FYI:  Testing locally with Docker Kubernetes, but plan on using with an EKS cluster.

**Comment by rpflynn22** [comment]
@whummer @cmeans wanted to see if any progress has been made here. I am running into the same issue, and have investigated a bit.

The `DOCKER_HOST` environment variable is used to initialize the docker client in localstack code [here](https://github.com/localstack/localstack/blob/1f72e552b8a2bd6739d648e4b6f06fb64350ebdb/localstack/utils/docker_utils.py#L1174). The `docker.from_env()` function is described in the Docker SDK for Python docs [here](https://docker-py.readthedocs.io/en/stable/client.html#docker.client.from_env).

I have `cat`-ed the `/proc/<pid>/environ` file for the localstack python PID and found `DOCKER_HOST` set correctly (to `tcp://localhost:2375`). Additionally, `docker context ls` on the pod outputs similarly correct config.

Interestingly, if you kill the localstack process, something (sorry, I don't have a good understanding of localstack's process management) restarts this process, _and everything works correctly!_

After some debugging (augmenting code with log statements, building localstack image locally), I found that the `SdkDockerClient`'s `__init__` function isn't called when the process is run, but it is called on subsequent runs (after killing the process). I'm not really sure how to figure out why this is happening, as it's hard to run the debugger in this context. If you can provide any pointers, I'd be glad to assist in making any changes. Thanks!

**Comment by nao23** [comment]
I think dind container must be running before localstack container started (exactly, before SdkDockerClient initialized) .

I modified manifests like below and it worked for me:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: default
spec:
  type: NodePort
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
      nodePort: 31566
    - name: es
      port: 4571
      targetPort: 4571
      nodePort: 31571
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: "localstack/localstack:latest"
          command:
            - /bin/bash
            - -c
            - |
              until (docker ps) do sleep 1; done
              docker-entrypoint.sh
          imagePullPolicy: IfNotPresent
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
            - name: es
              containerPort: 4571
              protocol: TCP
          volumeMounts:
            - name: dind-socket
              mountPath: /var/run/
            - name: dind-tls
              mountPath: /opt/docker/tls
          env:
            - name: LAMBDA_EXECUTOR
              value: "docker-reuse"
            - name: SERVICES
              value: "sqs,s3,lambda,ssm,logs"
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /opt/docker/tls/client
            - name: MAIN_CONTAINER_NAME
              value: localstack
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-1
        - name: dind
          image: "docker:20.10-dind"
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: "/opt/docker/tls"
          volumeMounts:
            - name: dind-socket
              mountPath: /var/run/
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: dind-tls
              mountPath: /opt/docker/tls
      volumes:
      - name: dind-socket
        emptyDir: {}
      - name: dind-storage
        emptyDir: {}
      - name: dind-tls
        emptyDir: {}
```
