### ISSUE TITLE
How to create localstack aws resources like a S3 bucket or SM secret?

### ISSUE THREAD

**Issue by ttj4** [localstack/helm-charts#23]
I do something like this in docker compose if I want to create a s3 bucket during start up

```
version: '3.8'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
```

and I have the following script in the aws local directory 
```
#!/bin/bash
set -x
awslocal s3 mb s3://bucket
set +x
```
Can someone help me to achieve something similar using helm chart?
