### ISSUE TITLE
Lambda not mounted in DinD container

### ISSUE THREAD

**Issue by kristapsstrals** [localstack/helm-charts#27]
Running kubernetes on Docker Desktop for Windows
Installed helm chart
`helm install localstack -n localstack--create-namespace localstack-charts/localstack -f ./values.localstack.yaml`
override file:
```yaml
debug: true
image:
  tag: "0.12.15"
lambdaExecutor: "docker-reuse"
mountDind:
  enabled: true
service:
  type: ClusterIP
ingress:
  enabled: true
  hosts:
    - host: localstack.localcluster
      paths:
        - /
```
Everything starts up normally, I can deploy my `netcoreapp3.1` function with an API gateway. Looking into the pod, I can also see the zipfile created at the 
However, when I execute the function, I get an exception that the `deps.json` is missing.
```
Could not find the required '<Project>.deps.json'. This file should be present at the root of the deployment package.: LambdaException
```
On further investigation, creating the container from the localstack pod with the same volume mount for zip file (`-v "/tmp/localstack/zipfile.2579021a":/var/task`) and checking inside the container, no files are actually mounted from the main `localstack` pod.

Looks like this could be related to the docker socket maybe not being mounted from the host system?

Tested this outside of kubernetes with `docker-compose` and by directly mounting the docker host in localstack and that worked.
```yaml
version: "3.0"

services:
  localstack-profile: #this is the name of the service.  Note: it is ALSO the name of a host created by Docker compose
    # image: localstack/localstack:0.12.11
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      # - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"

    environment:
      - DEFAULT_REGION=us-east-1 # regions must match (e.g. in serverless.yml)
      - SERVICES=acm,apigateway
        ,cloudformation,cloudwatch,dynamodb
        ,dynamodbstreams,ec2,es,events
        ,firehose,iam,kinesis,kms,lambda,rds
        ,route53,s3,s3api,secretsmanager,ses,sns
        ,sqs,ssm,stepfunctions,sts
      - DEBUG="1"
      - DATA_DIR=/tmp/localstack/data # for use by
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOVE_CONTAINERS=1
      - LAMBDA_DOCKER_NETWORK=profile-network # using a specified network to allow lambda to reach LocalStack
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      # - "${TMP_DIR:-/tmp/localstack}:${TMP_DIR:-/tmp/localstack}" # used for LocalStack internal data
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - profile-network

volumes:
  localstack-vol:
 networks:
   profile-network:
     name: profile-network
     driver: bridge

```
(though this example does not use a separate Docker in Docker image...)

If I manually create a kubernetes deployment that mounts the docker socket from the host and also create a volume on the host with `HostPath` then I can get this to work somewhat, but that seems a bit hacky. And in that case I have issues with connecting to other services running in the kubernetes cluster with the `<service>.<namespace>` hostname (although I don't know if this would be resolved if the chart docker lambda deployment above worked, since I don't quite understand how the network is shared with the docker-in-docker container...)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
           env:
             - name: DEFAULT_REGION
               value: "us-east-1"
             - name: SERVICES
               value: "acm,apigateway,cloudformation,cloudwatch,dynamodb,dynamodbstreams,ec2,es,events,firehose,iam,kinesis,kms,lambda,rds,route53,s3,s3api,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts"
             - name: DEBUG
               value: "1"
             - name: DATA_DIR
               value: "/tmp/localstack/data"
             - name: LAMBDA_EXECUTOR
               value: "docker-reuse"
             - name: LAMBDA_REMOVE_CONTAINERS
               value: "1"
             - name: DOCKER_HOST
               value: "unix:///var/run/docker.sock"
          volumeMounts:
            - name: docker-sock
              mountPath: "/var/run/"
            - name: datadir
              mountPath: "/tmp/localstack"
          securityContext:
            privileged: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/
        - name: datadir
          hostPath:
            path: /tmp/localstack

```

So my question is, does anyone know how to resolve the volume mount issues for the lambda in docker in docker from localstack pod?
