### ISSUE TITLE
Remove the default ingress-class 

### ISSUE THREAD

**Issue by mhaddon** [localstack/helm-charts#54]
By default the ingress class annotation is set:

```
ingress:
  enabled: false
  annotations:
    # Adjust the ingress class when not using nginx as incress controller
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
```

This causes issues if you want to unset this value to use the default ingress class.

The only solution I could find was setting annotations to be equal to an empty string, because otherwise helm merges any object you pass in.
