### ISSUE TITLE
livenessProbe and readinessProbe helm template misconfigured

### ISSUE THREAD

**Issue by rbisecke** [localstack/helm-charts#55]
Currently, this block is set for both proves in the deployment template ([deployment.yaml#L47-L56](https://github.com/localstack/helm-charts/blob/main/charts/localstack/templates/deployment.yaml#L47-L56)):
```yaml
httpGet:
  path: /health
  port: {{ .Values.service.edgeService.name }}
```

Unfortunately the port value should be `.Values.service.edgeService.targetPort`, otherwise this will always fail since it'll be hitting localhost:[name of service]/health rather than the actual port (i.e. `localhost:edge/health`)
