### ISSUE TITLE
LocalStack Lambda function requires docker.sock but LocalStack is not compatible with docker over tcp

### ISSUE THREAD

**Issue by Sarek-Wyona** [localstack/helm-charts#90]
Currently Lambda functions execution requires docker.sock. We want to run tests for lambda functions in our CI but the host docker.sock is not available (security) to use. 

We attempted to use the DIND container TCP docker host for the localstack container using the `DOCKER_HOST` environment variable on the localstack container. We created a deployment with DIND container and Localstack container and tired setting the `DOCKER_HOST` on the localstack container to `tcp://localhost:2375` (per our manifest).  

But, this environment variable is not respected because the variable is overwritten in localstack bootstrap.py as shown below. 

https://github.com/localstack/localstack/blob/master/localstack/utils/bootstrap.py#L542 

```# environment variables
    # pass through environment variables defined in config
    for env_var in config.CONFIG_ENV_VARS:
        value = os.environ.get(env_var, None)
        if value is not None:
            container.env_vars[env_var] = value
    container.env_vars["DOCKER_HOST"] = f"unix://{config.DOCKER_SOCK}"
```
    
**Expected behavior:** If the` DOCKER_HOST` environment variable is passed into the localstack container, the container should switch to using docker over tcp. 

**Actual behavior:** Localstack run fails with error `WARNING: Docker not available in the LocalStack container but required to run Lambda functions` because it is looking for the mounted docker.sock. 

This is a blocker for us as we cannot run Lambda tests in our CI.

**Comment by alexrashed** [comment]
Hi @Sarek-Wyona!
Could you give this another try? The function you are referencing is really only used by the CLI (which is not used in the Kubernetes setup at all). The `DOCKER_HOST` variable is still being used and should work as expected.
If you are still experiencing these issues, could you please add more details (including your config and the container logs)?
Thanks!

**Comment by Sarek-Wyona** [comment]
I am using golang to create the deployment. Here is what my deployment for DIND and LocalStack looks like when trying to use TCP. 

````
deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{ // Embedded
			Name:      req.objectName(),
			Namespace: req.Namespace,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &one,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": req.objectName(),
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{ // Embedded
					Labels: map[string]string{
						"app": req.objectName(),
					},
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:  "dind-sock",
							Image: "<registry_url>docker:dind-rootless",
							Ports: []corev1.ContainerPort{
								{
									ContainerPort: 2375,
									Protocol:      corev1.ProtocolTCP,
								},
							}, 
							Command: []string{"dockerd"},
							Args: []string{
								"-H",
								"unix://",
								"-H",
								"tcp://0.0.0.0:2375",
								"-D",
							},
							Resources: corev1.ResourceRequirements{
								Requests: corev1.ResourceList{
									corev1.ResourceCPU:    defaultRequestCPU,
									corev1.ResourceMemory: defaultRequestMem,
								},
								Limits: corev1.ResourceList{
									corev1.ResourceCPU:    defaultLimitCPU,
									corev1.ResourceMemory: defaultLimitMem,
								},
							},
							ImagePullPolicy: defaultImagePullPolicy,
							SecurityContext: &corev1.SecurityContext{
								Privileged: &defaultSecurityContext,
							},
						},
						{
							Name:  "localstack",
							Image: "<registry_url>localstack/localstack:2.0",
							Env:   req.Env,
							Args:  req.Args,
							Resources: corev1.ResourceRequirements{
								Requests: corev1.ResourceList{
									corev1.ResourceCPU: req.RequestCPU, corev1.ResourceMemory: req.RequestMem,
								},
								Limits: corev1.ResourceList{
									corev1.ResourceCPU:    req.LimitCPU,
									corev1.ResourceMemory: req.LimitMem,
								},
							},
							Ports: containerPorts,
							ImagePullPolicy: req.ImagePullPolicy,
						},
					},
				},
			},
		},
	}
````

I am then also setting `{Name: "DOCKER_HOST", Value: "tcp://localhost:2375"},` in the test. But, localstack fails to find docker and errors with 

```
2023-07-25T16:29:39.724 DEBUG --- [  MainThread] l.s.awslambda.urlrouter    : Registering parameterized Lambda routes.
2023-07-25T16:29:39.727 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='docker', value='localstack.services.awslambda.invocation.plugins:DockerRuntimeExecutorPlugin', group='localstack.lambda.runtime_executor')
2023-07-25T16:29:39.727 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.lambda.runtime_executor.docker = <class 'localstack.services.awslambda.invocation.plugins.DockerRuntimeExecutorPlugin'>)
2023-07-25T16:29:39.727 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.lambda.runtime_executor:docker
2023-07-25T16:29:39.729  WARN --- [  MainThread] l.s.a.i.docker_runtime_exe : WARNING: Docker not available in the LocalStack container but required to run Lambda functions. Please add the Docker volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. https://docs.localstack.cloud/references/lambda-provider-v2/#docker-not-available
```

Test log 

```
        	Error:      	Received unexpected error:
        	            	ResourceNotReady: failed waiting for successful resource state
```

**Comment by alexrashed** [comment]
Hi @Sarek-Wyona!
I'm sorry, there seems to be a bit of a confusion. This repo is about the `helm-chart` of LocalStack, as specifically maintained way of installing LocalStack in Kubernetes. It seems you are not using the helm chart in your code at all.
However, you can use the helm chart to create a working deployment for you:
```
$ helm repo add localstack https://localstack.github.io/helm-charts
$ helm repo update
$ helm template localstack/localstack --set "mountDind.enabled=True" --set "debug=True"
```
The last command will print a fully working LocalStack deployment file (including the DIND sidecar container and all the necessary configuration). I guess this working deployment would be quite helpful when debugging your issue.
Actually, I just tested the deployment in a newly created K3s cluster with exactly these parameters and it worked out of the box.

Here's a stripped down version of the `helm template` command output for your convenience:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  ...
  template:
    ...
    spec:
      ...
      containers:
        - name: localstack
          ...
          image: "localstack/localstack:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
            ...
          ...
          volumeMounts:
              - name: dind-tls
                mountPath: /opt/docker/tls
          env:
            - name: DEBUG
              value: "1"
            ...
            - name: LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT
              value: "60"
            - name: OVERRIDE_IN_DOCKER
              value: "1"
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /opt/docker/tls/client
        - name: dind
          image: "docker:20.10-dind"
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: "/opt/docker/tls"
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: dind-tls
              mountPath: /opt/docker/tls
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: dind-tls
        emptyDir: {}
```

Maybe you could even directly use the helm chart in your code? It is maintained and kept up to date.
I would also recommend to upgrade to the latest version (`2.2.0` at the time of writing this), since Lambda is being worked on a lot.

If you continue to struggle with the setup, please create an issue in `localstack/localstack`. This is the repo we use for general questions concerning LocalStack. If you do so, please feel free to ping me in a new issue over there, and reference this one.
Also, please add as much information as possible, most importantly the actual deployment (which can be extracted with `kubectl get deployment -o json <deployment-name>`). This would make it way easier for us to debug your issue (since we don't have to re-create and run your Go code).
With that being said, I will close this issue here for now. Thanks!
