### ISSUE TITLE
Using localstack and bitnami/mysql together result in: Error with executing "common.labels.standard"

### ISSUE THREAD

**Issue by mjasnowski** [localstack/helm-charts#92]
Hey Team, 
 
So we recently ran into an issue described here https://github.com/bitnami/charts/issues/18839 when using Local-Stack and Bitnami/MySQL together.. There was a change on my bitnami common side of things, which the latest Bitnami/MySQL chart is using), is causing this error when using these two charts together:

Our dependencies 
```
dependencies:
  - name: cht
    version: "^5.9"
    repository: "https://artifactory.mgmt.cloudhealthtech.com/artifactory/helm-virtual"
  - name: localstack
    repository: "https://helm.localstack.cloud"
    version: '^0.5.5'
    condition: localstack.local
  - name: mysql
    repository: "https://charts.bitnami.com/bitnami"
    version: '^9'
    condition: mysql.local
```

Error Summary:
```
helm | Error: template: notification/charts/mysql/templates/primary/svc.yaml:11:14: executing "notification/charts/mysql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: notification/charts/localstack/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: notification/charts/localstack/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm | helm.go:84: [debug] template: notification/charts/mysql/templates/primary/svc.yaml:11:14: executing "notification/charts/mysql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: notification/charts/localstack/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: notification/charts/localstack/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

The theory is that Local-Stack may need to be updated to a more recent (or at least compatible) version of Bitnami/Common. I did try the latest Local-Stack release 0.6.2 which is on 2.2 Bitnami/Common but the same issue persisted.

Thanks,
Mike
