### ISSUE TITLE
Feature Request: Ability to reference a secret for localstack api key

### ISSUE THREAD

**Issue by sobotklp** [localstack/helm-charts#96]
The documentation states that in order to pass the LOCALSTACK_API_KEY environment variable to the deployment, it should be done with `extraEnvVars` e.g.
```extraEnvVars:
  - name: LOCALSTACK_API_KEY
    value: "<your api key>"
```

Preferably, we'd like to avoid committing the key to a `values.yaml` file because the value would be in plain text. Ideally, we'd like to be able to pull the value out of a Kubernetes secret that may be defined by a parent chart or perhaps by IaC.

For example,
```
envFromSecret:
     - name: LOCALSTACK_API_KEY
       secret: localstack-secrets
       key: apiKey
```

where `localstack-secrets` may be defined like:
```
apiVersion: v1
kind: Secret
type: Opaque
data:
  apiKey: hello!
metadata:
  name: localstack-secrets
```

**Comment by alexrashed** [comment]
Hi @sobotklp!
Sorry for the late response. Actually, the `extraEnvVars` ist just a list of objects which are added to the env vars of the deployment. This means you can just reference a secret there:
```
extraEnvVars:
- name: LOCALSTACK_API_KEY
  valueFrom:
    secretKeyRef:
      name: <name of the secret containing the API key>
      key: <name of the key in the secret containing the API key>
```

I just updated the README and the `test-values.yaml` to make this more clear in the docs with https://github.com/localstack/helm-charts/commit/0e34a273fce7334d46188e2069c17fcd9a7db2fb.
I am sorry for the inconvenience. But thanks a lot for filing the PR. We really appreciate all contributions!
